#!/usr/bin/env python

"""
Build console script in directory specified by user.

If directory was not specified at execution time, build in current dir.
"""

import glob
import os
import shutil
import sys

try:
    import djtools
# this is for testing purposes
except ImportError:
    sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
    import djtools

# would be good not to overwrite old _djtools_common.py

if len(sys.argv) > 1:
    destdir = sys.argv[1]
else:
    destdir = os.getcwd()

for file in glob.glob(djtools.get_skel_dir() + '/*'):
    # do not copy special files if they already exists 
    filename = file.split('/')[-1]
    if filename.startswith('_'):
        try:
            open(os.path.join(destdir, filename))
        except IOError:
            shutil.copy(file, destdir)
    else:
        shutil.copy(file, destdir)